language: go
sudo: true
go:
  - 1.6
  - tip
install: true
script:
  - go list ./... | xargs -I{} sh -c "sudo -E $(which go) test -covermode=atomic -coverprofile=coverage.tmp {} && [ -f coverage.tmp ] && cat coverage.tmp >> coverage.txt && rm coverage.tmp"
after_success:
  - bash <(curl -s https://codecov.io/bash)
